export const experience = [
  {
    title: "Junior Frontend Developer",
    role: "Front End Web Developer",
    company: "PT Infosys Solusi Terpadu",
    period: "2021–2022",
    location: "Hybrid",
    desc: "Member Octo Clicks Teams which is a bank website that provides a secure and user-friendly banking experience. I worked on the front-end development of the website, including the design and implementation of the user interface. I also worked on the integration of the front-end with the back-end, including the implementation of the API calls. I also worked on the optimization of the website for performance and responsiveness.",
    highlights: [
      "Built the user interface for the Octo Clicks website, including the login page, dashboard, and transaction history page.",
      "Implemented the front-end of the website using React, Material UI, and JavaScript.",
      "Integrated the front-end with the back-end using Axios, Redux, and Gitlab.",
      "Optimized the website for performance and responsiveness, resulting in a faster loading time and improved user experience.",
    ],
    tech: ["React", "Material UI", "JavaScript", "Axios", "Redux", "Gitlab"],
  },
  {
    title: "IT Programmer",
    role: "IT Programmer",
    company: "Natieva",
    period: "2022–2023",
    location: "Remote",
    desc: "I build full-stack websites, web applications, and landing pages using modern technologies, including AI. At Natieva, I specialize in developing CMS platforms, LMS systems, landing pages, and mobile applications.",
    highlights: [
      "Design system",
      "LMS system",
      "landing page",
      "mobile application",
      "AI integration",
      "CMS platform",
    ],
    tech: [
      "React",
      "TypeScript",
      "Jotai",
      "React Query",
      "React Router",
      "Laravel",
      "PHP",
      "JavaScript",
      "Zustand",
      "Next.js",
      "Tailwind CSS",
      "MySQL",
    ],
  },
  {
    title: "React Developer",
    role: "Frontend Engineer & Hybrid Developer",
    company: "CV Technopartner Indonesia",
    period: "2024–now",
    location: "On-site",
    desc: "In Technopartner Indonesia, I work as a React Developer. I specialize in building web applications using React, Next.js, and Tailwind CSS. I also work on the design system and component library evolution. I am also responsible for the documentation and guidelines. I also work on the PR reviews and mentoring. I am also responsible for the accessibility checks.",
    highlights: [
      "Design system governance",
      "Component library evolution",
      "Docs and guidelines",
      "PR reviews & mentoring",
      "Accessibility checks",
    ],
    tech: [
      "React",
      "Next.js",
      "Tailwind CSS",
      "React Native",
      "React Query",
      "Redux",
    ],
  },
];
