export type Project = {
  title: string;
  desc: string;
  category: string;
  year?: number;
  href?: string;
  thumb?: string;
  points?: string[];
  stack?: string[];
  id?: string;
};

// Export projects data for use in other components
export const projects: Project[] = [
  {
    id: "octo-clicks",
    title: "Octo Clicks",
    desc: "A secure and user-friendly banking website with features like account management, transaction history, and real-time balance updates.",
    category: "Banking Website",
    year: 2022,
    href: "/projects/octo-clicks",
    thumb: "OC.jpg",
    points: [
      "Consistent UI",
      "Pixel-perfect",
      "Responsive design",
      "Shared components",
    ],
    stack: [
      "React",
      "Material UI",
      "JavaScript",
      "Axios",
      "Redux",
      "Gitlab",
      "Axios",
    ],
  },
  {
    id: "luna-sinarmas",
    title: "LUNA by MSIG Life",
    desc: "LUNA by MSIG Life is a digital learning hub designed to support the training and professional development of MSIG Life's sales and marketing personnel. It is not a customer-facing product but an internal-facing application to improve the quality of the company's agents.",
    category: "LMS Website",
    year: 2023,
    href: "/projects/luna-sinarmas",
    thumb: "luna.png",
    points: [
      "Consistent UI",
      "Faster delivery",
      "Learning platform",
      "Interactive modules",
      "Mobile-responsive",
    ],
    stack: ["React", "TypeScript", "Jotai", "React Query", "React Router"],
  },
  {
    id: "natieva-landing-page",
    title: "Natieva Landing Page",
    desc: "An elegant landing page for an online English-learning platform, connecting learners with native speakers",
    category: "Landing Page",
    year: 2023,
    href: "/projects/natieva-landing-page",
    thumb: "natieva.jpeg",
    points: ["SEO-friendly", "Mobile-responsive", "Fast loading"],
    stack: ["Laravel", "Blade", "Tailwind CSS", "JavaScript", "jQuery", "PHP"],
  },
  {
    id: "natieva-dashboard",
    title: "Natieva Corporate",
    desc: "Web dashboard for Natieva, a platform that connects learners with native speakers",
    category: "LMS Dashboard",
    year: 2023,
    href: "/projects/natieva-dashboard",
    thumb: "natieva.jpeg",
    points: ["Dashboard", "Scheduling", "Learning Platform"],
    stack: [
      "Next.js",
      "React",
      "Zustand",
      "AI integration",
      "React Query",
      "React Router",
      "Iframe",
      "Speech synthesis",
      "Fullcalendar integration",
    ],
  },
  {
    id: "natieva-cms",
    title: "Natieva CMS",
    desc: "Web CMS for configure platform and manage users.",
    category: "Web CMS",
    year: 2023,
    href: "/projects/natieva-cms",
    thumb: "natieva.jpeg",
    points: [
      "Full-featured CMS",
      "User management",
      "Role-based access",
      "Content management",
      "Speaker management",
      "Event scheduling",
      "Analytics dashboard",
    ],
    stack: [
      "Laravel",
      "Blade",
      "Tailwind CSS",
      "JavaScript",
      "jQuery",
      "MySQL",
      "PHP",
    ],
  },
  {
    id: "natieva-mobile",
    title: "Natieva Mobile",
    desc: "Natieva Mobile is a mobile application for Natieva, a platform that connects learners with native speakers",
    category: "Mobile App",
    year: 2023,
    href: "/projects/natieva-mobile",
    thumb: "natieva-mobile.png",
    points: [
      "Mobile-responsive",
      "Fast loading",
      "User-friendly",
      "Mobile App",
      "AI integration",
      "Audio synthesis",
    ],
    stack: [
      "React Native",
      "JavaScript",
      "TypeScript",
      "React Query",
      "React Router",
      "Context",
      "AI integration",
      "Fullcalendar",
      "Character animation",
    ],
  },
  {
    id: "natieva-kids-dashboard",
    title: "Natieva Kids Dashboard",
    desc: "Web dashboard for Natieva Kids, a platform that connects learners with native speakers",
    category: "LMS Dashboard",
    year: 2023,
    href: "/projects/natieva-kids-dashboard",
    thumb: "natieva-kids.jpg",
    points: ["Dashboard", "Scheduling", "Learning Platform"],
    stack: [
      "Next.js",
      "React",
      "Zustand",
      "AI integration",
      "React Query",
      "React Router",
      "Iframe",
      "Speech synthesis",
      "Fullcalendar integration",
    ],
  },
  {
    id: "natieva-kids-mobile",
    title: "Natieva Kids Mobile App",
    desc: "Natieva Kids is a mobile application for Natieva, a platform that connects learners with native speakers",
    category: "Mobile App",
    year: 2023,
    href: "/projects/natieva-kids",
    thumb: "natieva-kids.jpg",
    points: [
      "Mobile-responsive",
      "Fast loading",
      "User-friendly",
      "Mobile App",
      "AI integration",
      "Audio synthesis",
    ],
    stack: [
      "React Native",
      "JavaScript",
      "TypeScript",
      "React Query",
      "React Router",
      "Context",
      "AI integration",
      "Fullcalendar",
      "Character animation",
    ],
  },
  {
    id: "casion",
    title: "Casion",
    desc: "Casion is an application that used for find charging station and this application used for charging vehicle",
    category: "Mobile App",
    year: 2024,
    href: "/projects/casion",
    thumb: "casion.png",
    points: [
      "Find charging station",
      "Charging vehicle",
      "Real-time tracking",
      "User-friendly",
    ],
    stack: [
      "React Native",
      "JavaScript",
      "TypeScript",
      "React Query",
      "React Router",
      "Redux",
      "Maps",
      "Barcode Scanner",
    ],
  },
];
